# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Multmat <- function(tmm, tm22) {
    .Call('_reSNP_Multmat', PACKAGE = 'reSNP', tmm, tm22)
}

arrayC <- function(input, dim) {
    .Call('_reSNP_arrayC', PACKAGE = 'reSNP', input, dim)
}

colMax <- function(m) {
    .Call('_reSNP_colMax', PACKAGE = 'reSNP', m)
}

gridG <- function(g, seqx) {
    .Call('_reSNP_gridG', PACKAGE = 'reSNP', g, seqx)
}

rowMax <- function(m) {
    .Call('_reSNP_rowMax', PACKAGE = 'reSNP', m)
}

trueG <- function(g, c) {
    .Call('_reSNP_trueG', PACKAGE = 'reSNP', g, c)
}

